//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerShell.SHiPS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerShell.SHiPS.Resources", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an instance of type &apos;{0}&apos; in the module &apos;{1}&apos;. Make sure type &apos;{0}&apos; exists, inherits from Microsoft.PowerShell.SHiPS.SHiPSDirectory, and Name is set in constructors. As a root, a constructor &apos;{0}([string]$name)&apos;  is required. Fix the script and try again..
        /// </summary>
        internal static string CannotCreateInstance {
            get {
                return ResourceManager.GetString("CannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find module &apos;{0}&apos;..
        /// </summary>
        internal static string CannotGetModule {
            get {
                return ResourceManager.GetString("CannotGetModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find base Powershell module folder..
        /// </summary>
        internal static string CantFindBaseModuleFolder {
            get {
                return ResourceManager.GetString("CantFindBaseModuleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring data for &apos;{0}&apos; ....
        /// </summary>
        internal static string FetchingData {
            get {
                return ResourceManager.GetString("FetchingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found invalid root format &apos;{0}&apos;. The supported format is &apos;Module#Class&apos;..
        /// </summary>
        internal static string InvalidRootFormat {
            get {
                return ResourceManager.GetString("InvalidRootFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A root node must be derived from Microsoft.PowerShell.SHiPS.SHiPSDirectory..
        /// </summary>
        internal static string InvalidRootNode {
            get {
                return ResourceManager.GetString("InvalidRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found root node type is set to &apos;{0}&apos;. A root node must be derived from Microsoft.PowerShell.SHiPS.SHiPSDirectory..
        /// </summary>
        internal static string InvalidRootNodeType {
            get {
                return ResourceManager.GetString("InvalidRootNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking PowerShell script &apos;{0}&apos; for path &apos;{1}&apos; returns null or empty..
        /// </summary>
        internal static string InvokeScriptReturnNull {
            get {
                return ResourceManager.GetString("InvokeScriptReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; may no longer exists. Details: {1}..
        /// </summary>
        internal static string MaybeItemNotExist {
            get {
                return ResourceManager.GetString("MaybeItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a child node of &apos;{0}&apos; has name with null or empty string. Make sure name is set properly in the constructors..
        /// </summary>
        internal static string NameWithNullOrEmpty {
            get {
                return ResourceManager.GetString("NameWithNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive root does not exist. .
        /// </summary>
        internal static string NewDriveRootDoesNotExist {
            get {
                return ResourceManager.GetString("NewDriveRootDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under &apos;{0}&apos; node, found multiple child nodes have the same name &apos;{1}&apos;. Fix the script and try again..
        /// </summary>
        internal static string NodesWithSameName {
            get {
                return ResourceManager.GetString("NodesWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data.
        /// </summary>
        internal static string RetrievingData {
            get {
                return ResourceManager.GetString("RetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying &apos;{0}&apos;..
        /// </summary>
        internal static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;{0}&apos; at &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToFindModule {
            get {
                return ResourceManager.GetString("UnableToFindModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node at path &apos;{0}&apos; may not support the cmdlet &apos;{1}&apos;..
        /// </summary>
        internal static string UnSupportedCmdlet {
            get {
                return ResourceManager.GetString("UnSupportedCmdlet", resourceCulture);
            }
        }
    }
}
